# Generated by Django 4.1 on 2023-03-08 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('first_name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('payee_user_name', models.CharField(max_length=30)),
                ('payer_user_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Owe_app.userinfo')),
            ],
        ),
    ]
