# Generated by Django 4.1 on 2023-03-08 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owe_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transactions',
            new_name='Transaction',
        ),
    ]
