# Generated by Django 4.1 on 2023-03-09 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Owe_app', '0002_rename_transactions_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='payee_user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Payee_User_Name', to='Owe_app.userinfo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='payer_user_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Payer_User_Name', to='Owe_app.userinfo'),
        ),
    ]
