# Generated by Django 4.1 on 2023-03-09 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owe_app', '0004_transaction_time_stamp_transaction_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='time_stamp',
        ),
    ]
